version: '3.9'

networks:
  node-network:
    driver: bridge

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: allio
    volumes:
      - dbdata:/data/postgres
    ports:
      - 15432:5432
    networks:
      - node-network

services:
  nest-app:
    build: .
    image: nest_app
    container_name: nest_app_container
    env_file: .env
    environment:
      - POSTGRES_HOST=postgres
    ports:
      - '5010:5010'
    depends_on:
      - postgres
    volumes:
      - .:/var/www
    networks:
      - node-network

volumes:
  dbdata:
  pgadmin:
  node_modules:
