version: '3.9'

networks:
  node-network:
    driver: bridge

services:
  nest-app:
    build: .
    image: nest_app
    container_name: nest_app_container
    environment:
      - POSTGRES_HOST=postgres
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    volumes:
      - .:/var/www
    networks:
      - node-network

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: allio
    volumes:
      - dbdata:/data/postgres
    ports:
      - 15432:5432
    networks:
      - node-network

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/root/.pgadmin
    depends_on:
      - postgres
    ports:
      - '${PGADMIN_PORT:-5050}:80'
    networks:
      - node-network

volumes:
  dbdata:
  pgadmin:
  node_modules:
